name: Frontend test

on:
  push:
    branches: [ "fki-CI-setup" ]
  pull_request:
    branches: [ "fki-CI-setup" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: fki-Frontend-tests
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run tests CI tests
      run: |
        cd FontendTests/adoptAPetFrontend
        mvn test -Dcucumber.filter.tags="@testCI"


